name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      activity:
        description: 'What activity do you intend to do?'
        type: choice
        options:
        - Pre-Activity
        - Post-Activity
      environment:
        description: 'What environment you are doing the activity checks?'
        type: choice
        options:
        - Test-US
        - UAT-US

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "You are tryting to do ${{ github.event.inputs.activity }}!"
          echo "- in ${{ github.event.inputs.environment }}!"
          ping LPRSRDSBADM002V
          
