# This is a basic workflow to help you get started with Actions

name: TestSSH

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      activity:
        description: 'What activity do you intend to do?'
        type: choice
        options:
        - Pre-Activity
        - Post-Activity
      environment:
        description: 'What environment you are doing the activity checks?'
        type: choice
        options:
        - Test-US
        - UAT-US

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY_TEST" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST_TEST
            User $SSH_USER_TEST
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
          env:
            SSH_USER: ${{ secrets.STAGING_SSH_USER_TEST }}
            SSH_KEY: ${{ secrets.STAGING_SSH_KEY_TEST }}
            SSH_HOST: ${{ secrets.STAGING_SSH_HOST_TEST }}
      - name: List in the server
        run: ssh staging 'ls -lrt /home/kevinjames.bajao/'
      - name: Echo output
        - run: |
          echo "You are tryting to do ${{ github.event.inputs.activity }}!"
          echo "- in ${{ github.event.inputs.environment }}!"
